name: Amazing Workflow

on:
  pull_request:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Show Pipeline Details
        run: |
          echo "Pull Request Title"
          echo ${{ github.event.pull_request.title }}
          echo "_____"
          echo "Commit Message"
          echo ${{ github.event.head_commit.message }}

      - name: Docker
        run: |
          echo "Execute Docker pull"
          docker pull ubuntu:18.04

      - name: Codecov
        if: false
        run: |
          curl -0s https://uploader.codecov.io/latest/codecov
          chmod +x codecov
          ./codecov -t dfg234-4f54-2334-8c0f-r34tq5
